import Head from 'next/head';
// import Image from 'next/image';
import styles from '../assets/styles/Home.module.scss';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Main from '../components/Main';
import Compare from '../components/Compare';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div className={styles.page}>
      <Head>
        <title>Shaffofyul</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Compare />
      <Contact />
      <Footer />
    </div>
  )
}
